USE [master]
GO

/****** Object:  Database [SuperZapatos]    Script Date: 8/3/2016 11:14:24 AM ******/
CREATE DATABASE [SuperZapatos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SuperZapatos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SuperZapatos_Primary.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SuperZapatos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SuperZapatos_Primary.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SuperZapatos] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SuperZapatos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SuperZapatos] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [SuperZapatos] SET ANSI_NULLS ON 
GO

ALTER DATABASE [SuperZapatos] SET ANSI_PADDING ON 
GO

ALTER DATABASE [SuperZapatos] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [SuperZapatos] SET ARITHABORT ON 
GO

ALTER DATABASE [SuperZapatos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SuperZapatos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SuperZapatos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SuperZapatos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SuperZapatos] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [SuperZapatos] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [SuperZapatos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SuperZapatos] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [SuperZapatos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SuperZapatos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SuperZapatos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SuperZapatos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SuperZapatos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SuperZapatos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SuperZapatos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SuperZapatos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SuperZapatos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SuperZapatos] SET RECOVERY FULL 
GO

ALTER DATABASE [SuperZapatos] SET  MULTI_USER 
GO

ALTER DATABASE [SuperZapatos] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [SuperZapatos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SuperZapatos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SuperZapatos] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SuperZapatos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SuperZapatos] SET  READ_WRITE 
GO

USE [SuperZapatos]
GO
/****** Object:  Table [dbo].[Stores]    Script Date: 8/3/2016 11:13:32 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Stores](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Address] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
/****** Object:  Table [dbo].[Articles]    Script Date: 8/3/2016 11:13:32 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Articles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Description] [text] NOT NULL,
	[Price] [decimal](18, 3) NOT NULL,
	[Total_In_Shelf] [int] NOT NULL DEFAULT ((0)),
	[Total_In_Vault] [int] NOT NULL DEFAULT ((0)),
	[StoreId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[Articles]  WITH CHECK ADD  CONSTRAINT [FK_Articles_Stores] FOREIGN KEY([StoreId])
REFERENCES [dbo].[Stores] ([Id])
GO
ALTER TABLE [dbo].[Articles] CHECK CONSTRAINT [FK_Articles_Stores]
GO

USE [master]
GO
CREATE LOGIN [developer] WITH PASSWORD=N'developer123', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [developer]
GO
USE [master]
GO
--CREATE USER [developer] FOR LOGIN [developer]
--GO
USE [master]
GO
ALTER ROLE [db_owner] ADD MEMBER [developer]
GO
USE [SuperZapatos]
GO
CREATE USER [developer] FOR LOGIN [developer]
GO
USE [SuperZapatos]
GO
ALTER ROLE [db_owner] ADD MEMBER [developer]
GO
