//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperZapatos.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SuperZapatosContext : DbContext
    {
        public SuperZapatosContext()
            : base("name=SuperZapatosContext")
        {
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
    }
}
